e22: '30'
e24: Right
e26: ''
e28: ''
e32: '30'
e34: Left
e36: ''
e38: ''
e44: Up
e46: ''
e48: ''
e54: Down
e56: ''
e58: ''
e64: Alt
e66: p
e68: ''
e72: liked
e74: Ctrl
e76: l
e78: ''
e82: maybe
e84: Ctrl
e86: m
e88: ''
e92: nope
e94: Ctrl
e96: n
e98: ''
